import {DEFAULT_ORB_POLICY,shortestSeparation} from '../kernel/noetic-kernel.mjs';
import {classicalDispositorSubgraph,functionalDigraphAnalytics} from './graph-analytics-engine.mjs';

export const HYPERGRAPH_VERSION='0.4.7';
export const HYPERGRAPH_MODEL='naf.research.astrological_hypergraph.v0.4.7';
export const HYPEREDGE_SCHEMA='naf.research.hyperedge.v0.4.7';
export const HYPERGRAPH_DERIVATION_MODEL='naf.research.hyperedge_derivation.v0.4.7';

const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
const H0=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
const rotr=(x,n)=>(x>>>n)|(x<<(32-n));
export function sha256Hex(text){
  const bytes=new TextEncoder().encode(String(text)),bitLen=bytes.length*8,total=Math.ceil((bytes.length+9)/64)*64,data=new Uint8Array(total);data.set(bytes);data[bytes.length]=0x80;const dv=new DataView(data.buffer);dv.setUint32(total-8,Math.floor(bitLen/0x100000000),false);dv.setUint32(total-4,bitLen>>>0,false);const h=[...H0],w=new Uint32Array(64);
  for(let off=0;off<total;off+=64){for(let i=0;i<16;i++)w[i]=dv.getUint32(off+i*4,false);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3),s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,hh]=h;for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^((~e)&g),t1=(hh+S1+ch+K[i]+w[i])>>>0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;hh=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}h[0]=(h[0]+a)>>>0;h[1]=(h[1]+b)>>>0;h[2]=(h[2]+c)>>>0;h[3]=(h[3]+d)>>>0;h[4]=(h[4]+e)>>>0;h[5]=(h[5]+f)>>>0;h[6]=(h[6]+g)>>>0;h[7]=(h[7]+hh)>>>0}
  return h.map(x=>x.toString(16).padStart(8,'0')).join('');
}
const mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const rms=xs=>Math.sqrt(mean(xs.map(x=>x*x)));
const sd=xs=>{if(xs.length<2)return 0;const m=mean(xs);return Math.sqrt(xs.reduce((s,x)=>s+(x-m)**2,0)/(xs.length-1))};
const deepFreeze=x=>{if(!x||typeof x!=='object'||Object.isFrozen(x))return x;for(const v of Object.values(x))deepFreeze(v);return Object.freeze(x)};
const uniq=xs=>[...new Set((xs||[]).filter(Boolean))];
const canonical=x=>JSON.stringify(x,Object.keys(x||{}).sort());
function combinations(xs,k){const out=[];function rec(start,row){if(row.length===k){out.push([...row]);return}for(let i=start;i<=xs.length-(k-row.length);i++){row.push(xs[i]);rec(i+1,row);row.pop()}}rec(0,[]);return out}
function permutations(xs){if(xs.length<2)return [[...xs]];const out=[];for(let i=0;i<xs.length;i++){const head=xs[i],rest=[...xs.slice(0,i),...xs.slice(i+1)];for(const tail of permutations(rest))out.push([head,...tail])}return out}
function objectClass(o){if(o?.type==='planet')return ['Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn'].includes(o.id)?'classical_planet':'outer_planet';if(o?.type==='minor_body')return 'minor_body';if(o?.type==='lot')return 'lot';if(o?.type==='node')return 'node';return o?.type||'derived'}
export function hypergraphObjects(analysis,{include_angles=false}={}){const xs=[...(analysis?.objects||[]),...(analysis?.lots||[]),...(include_angles?[analysis?.angles?.ASC,analysis?.angles?.MC]:[])].filter(o=>o?.id&&Number.isFinite(Number(o.longitude)));const seen=new Set();return xs.filter(o=>{if(seen.has(o.id))return false;seen.add(o.id);return true}).map(o=>({id:o.id,type:o.type||'derived',object_class:objectClass(o),longitude:Number(o.longitude),sign:o.sign||null,computed_house:o.computed_house??null}))}

export const CONFIGURATION_ORB_POLICY=deepFreeze({
  id:'naf.hypergraph.configuration_orbs.v1',
  basis:'Noetic research policy; major-aspect ceilings inherit the kernel default orb policy while multi-body RMS thresholds are deliberately stricter.',
  aspect_limits:{conjunction:Math.min(6,DEFAULT_ORB_POLICY.conjunction),sextile:DEFAULT_ORB_POLICY.sextile,square:Math.min(8,DEFAULT_ORB_POLICY.square),trine:Math.min(8,DEFAULT_ORB_POLICY.trine),opposition:Math.min(8,DEFAULT_ORB_POLICY.opposition),quincunx:3},
  rms_limits:{grand_trine:5,t_square:5,yod:2.5,grand_cross:5,kite:5,t_square_anchor_cluster:2.5}
});

const TEMPLATES=[
 {id:'grand_trine',label:'Grand Trine',cardinality:3,edges:[[0,1,120,'trine'],[1,2,120,'trine'],[0,2,120,'trine']],historical_basis:'The trine is the 120° side of an inscribed triangle; the whole-pattern name is modern.',source_lock:['Brennan 2017 ch.9 configurations/polygons','Woolfolk 2008 lexicon: Grand Trine']},
 {id:'t_square',label:'T-Square',cardinality:3,edges:[[0,1,180,'opposition'],[0,2,90,'square'],[1,2,90,'square']],historical_basis:'Opposition and square angles are classical; the three-body T-Square template is a modern named configuration.',source_lock:['Brennan 2017 ch.9 degree configurations','Woolfolk 2008 lexicon: T-square']},
 {id:'yod',label:'Yod',cardinality:3,edges:[[0,1,60,'sextile'],[0,2,150,'quincunx'],[1,2,150,'quincunx']],historical_basis:'Noetic v1 modern configuration template; not represented as a Hellenistic named figure.',source_lock:['Noetic Atlas configuration template registry v1']},
 {id:'grand_cross',label:'Grand Cross',cardinality:4,edges:[[0,1,90,'square'],[1,2,90,'square'],[2,3,90,'square'],[3,0,90,'square'],[0,2,180,'opposition'],[1,3,180,'opposition']],historical_basis:'Square/opposition angles are classical; the four-body Grand Cross whole-pattern name is modern.',source_lock:['Brennan 2017 ch.9 configurations/polygons','Woolfolk 2008 lexicon: Grand Cross']},
 {id:'kite',label:'Kite',cardinality:4,edges:[[0,1,120,'trine'],[1,2,120,'trine'],[0,2,120,'trine'],[3,0,180,'opposition'],[3,1,60,'sextile'],[3,2,60,'sextile']],historical_basis:'Noetic v1 modern configuration template assembled from classical major-angle relations.',source_lock:['Brennan 2017 ch.9 degree configurations','Noetic Atlas configuration template registry v1']},
 {id:'t_square_anchor_cluster',label:'T-Square Anchor Cluster',cardinality:4,edges:[[0,1,0,'conjunction'],[2,3,180,'opposition'],[0,2,90,'square'],[0,3,90,'square'],[1,2,90,'square'],[1,3,90,'square']],historical_basis:'Noetic Discovery template: a close conjunction acts as a doubled square anchor to an opposition axis. This is not asserted as an inherited named doctrine.',source_lock:['Noetic Atlas configuration template registry v1']}
].map(t=>deepFreeze({...t,max_orb_deg:Math.max(...t.edges.map(e=>CONFIGURATION_ORB_POLICY.aspect_limits[e[3]])),rms_orb_deg:CONFIGURATION_ORB_POLICY.rms_limits[t.id]}));
export const GEOMETRIC_CONFIGURATION_TEMPLATES=deepFreeze(TEMPLATES);
export function getConfigurationTemplate(id){const t=GEOMETRIC_CONFIGURATION_TEMPLATES.find(x=>x.id===id);if(!t)throw new Error(`Unknown configuration template: ${id}`);return t}

function fitPermutation(ids,byId,t){const residuals=[],edgeRows=[];for(const [i,j,target,aspect] of t.edges){const a=byId[ids[i]],b=byId[ids[j]];if(!a||!b)return null;const separation=shortestSeparation(a.longitude,b.longitude),orb=Math.abs(separation-target),limit=CONFIGURATION_ORB_POLICY.aspect_limits[aspect];residuals.push(orb);edgeRows.push({a:a.id,b:b.id,target_angle_deg:target,aspect,separation_deg:separation,orb_deg:orb,orb_limit_deg:limit})}const maxOrb=Math.max(...residuals),rmsOrb=rms(residuals),valid=edgeRows.every(e=>e.orb_deg<=e.orb_limit_deg)&&rmsOrb<=t.rms_orb_deg;return {valid,ordered_nodes:ids,edges:edgeRows,max_orb_deg:maxOrb,rms_orb_deg:rmsOrb,residual_sd_deg:sd(residuals),symmetry_index:Math.max(0,Math.min(1,1-rmsOrb/t.rms_orb_deg))}}
export function fitConfigurationTemplate(participantIds,objects,templateId){const t=typeof templateId==='string'?getConfigurationTemplate(templateId):templateId,byId=Array.isArray(objects)?Object.fromEntries(objects.map(o=>[o.id,o])):objects;let best=null;for(const p of permutations(participantIds)){const r=fitPermutation(p,byId,t);if(!r)continue;if(!best||r.rms_orb_deg<best.rms_orb_deg-1e-12||(Math.abs(r.rms_orb_deg-best.rms_orb_deg)<1e-12&&r.max_orb_deg<best.max_orb_deg))best=r}return best}
function derivationHash(payload){return sha256Hex(JSON.stringify(payload))}
function baseStatus(){return {vector:[1,1,0,0,0],dimensions:{detection:'detected',verification:'verified',null_comparison:'pending',population_frequency:'unknown',interpretation:'withheld'},rule:'Detection and derivation are complete; null comparison is required before baseline promotion. Population frequency and interpretation remain withheld.'}}
function geometricHyperedge(t,fit,objects){const participants=[...fit.ordered_nodes],sorted=[...participants].sort(),payload={model:HYPERGRAPH_DERIVATION_MODEL,template:t.id,participants:sorted,edges:fit.edges.map(e=>({a:e.a,b:e.b,target:e.target_angle_deg,separation:e.separation_deg,orb:e.orb_deg})),orb_policy:CONFIGURATION_ORB_POLICY.id};const hash=derivationHash(payload);return {schema:HYPEREDGE_SCHEMA,hyperedge_id:`geom.${t.id}.${sorted.join('.')}.${hash.slice(0,12)}`,hyperedge_class:'geometric_polygon',configuration_type:t.id,label:t.label,participating_nodes:participants,participant_classes:Object.fromEntries(participants.map(id=>[id,objects.find(o=>o.id===id)?.object_class||'unknown'])),required_cardinality:t.cardinality,geometric_metrics:{target_angles:t.edges.map(e=>e[2]),max_orb_deg:fit.max_orb_deg,rms_orb_deg:fit.rms_orb_deg,residual_sd_deg:fit.residual_sd_deg,symmetry_index:fit.symmetry_index,matched_edges:fit.edges,orb_policy_id:CONFIGURATION_ORB_POLICY.id},topological_metrics:null,derivation_hash:hash,derivation_hash_algorithm:'sha-256',derivation:{model:HYPERGRAPH_DERIVATION_MODEL,source_lock:t.source_lock,historical_basis:t.historical_basis,input_payload:payload},research_status:baseStatus(),null_profile:null,population_frequency:'unknown',interpretation_status:'withheld'} }
export function detectGeometricHyperedges(analysis,options={}){const objects=hypergraphObjects(analysis,options),ids=objects.map(o=>o.id),out=[];for(const t of GEOMETRIC_CONFIGURATION_TEMPLATES){for(const combo of combinations(ids,t.cardinality)){const fit=fitConfigurationTemplate(combo,objects,t);if(fit?.valid)out.push(geometricHyperedge(t,fit,objects))}}return out.sort((a,b)=>a.configuration_type.localeCompare(b.configuration_type)||a.hyperedge_id.localeCompare(b.hyperedge_id))}

function topoHash(kind,participants,extra){return derivationHash({model:HYPERGRAPH_DERIVATION_MODEL,kind,participants:[...participants].sort(),extra})}
export function detectTopologicalHyperedges(analysis){const graph=classicalDispositorSubgraph(analysis),fd=functionalDigraphAnalytics(graph),out=[];for(const c of fd.condensation.nodes.filter(x=>x.members.length>=2)){const participants=[...c.members].sort(),basin=fd.terminal_basins.find(b=>b.component_id===c.id),hash=topoHash('scc',participants,{component_id:c.id,terminal:c.terminal,edges:graph.edges.filter(e=>participants.includes(e.from)&&participants.includes(e.to))});out.push({schema:HYPEREDGE_SCHEMA,hyperedge_id:`topo.scc.${participants.join('.')}.${hash.slice(0,12)}`,hyperedge_class:'topological_basin',configuration_type:'dispositor_scc',label:'Closed Dispositor SCC',participating_nodes:participants,participant_classes:Object.fromEntries(participants.map(id=>[id,'classical_planet'])),required_cardinality:participants.length,geometric_metrics:null,topological_metrics:{scc_id:`classical.scc.${c.id}`,is_closed_cycle:true,is_terminal:c.terminal,basin_volume:basin?.basin_size??participants.length,basin_fraction:basin?.basin_fraction??null,basin_members:basin?.basin_members??participants},derivation_hash:hash,derivation_hash_algorithm:'sha-256',derivation:{model:HYPERGRAPH_DERIVATION_MODEL,calculation:'Tarjan SCC promoted from classical dispositor graph',source_graph:'traditional domicile dispositor graph',edges:graph.edges.filter(e=>participants.includes(e.from)&&participants.includes(e.to))},research_status:baseStatus(),null_profile:null,population_frequency:'unknown',interpretation_status:'withheld'})}
  for(const b of fd.terminal_basins.filter(x=>x.basin_members.length>=2)){const participants=[...b.basin_members].sort(),hash=topoHash('basin',participants,{terminal_members:b.terminal_members,basin_fraction:b.basin_fraction});out.push({schema:HYPEREDGE_SCHEMA,hyperedge_id:`topo.basin.${b.terminal_members.join('.')}.${hash.slice(0,12)}`,hyperedge_class:'topological_basin',configuration_type:'terminal_basin_capture',label:'Terminal Basin Capture',participating_nodes:participants,participant_classes:Object.fromEntries(participants.map(id=>[id,'classical_planet'])),required_cardinality:participants.length,geometric_metrics:null,topological_metrics:{scc_id:`terminal.${b.terminal_members.join('.')}`,is_closed_cycle:b.terminal_members.length>=2,basin_volume:b.basin_size,basin_fraction:b.basin_fraction,basin_members:participants,terminal_members:b.terminal_members},derivation_hash:hash,derivation_hash_algorithm:'sha-256',derivation:{model:HYPERGRAPH_DERIVATION_MODEL,calculation:'functional-digraph basin capture',formula:'B(C)={v:v→*C}',source_graph:'traditional domicile dispositor graph'},research_status:baseStatus(),null_profile:null,population_frequency:'unknown',interpretation_status:'withheld'})}
  return out.sort((a,b)=>a.hyperedge_id.localeCompare(b.hyperedge_id))}

export function detectCompoundHybridHyperedges(analysis,geometric=null){const geoms=geometric||detectGeometricHyperedges(analysis),graph=classicalDispositorSubgraph(analysis),fd=functionalDigraphAnalytics(graph),classical=new Set(graph.nodes),basinOf={};fd.terminal_basins.forEach((b,i)=>b.basin_members.forEach(n=>basinOf[n]=i));const out=[];for(const g of geoms){const cp=g.participating_nodes.filter(n=>classical.has(n));if(cp.length<2)continue;const groups={};for(const n of cp){const k=basinOf[n];if(k===undefined)continue;(groups[k]||=[]).push(n)}const shared=Object.entries(groups).map(([k,nodes])=>({basin_index:Number(k),nodes})).sort((a,b)=>b.nodes.length-a.nodes.length)[0];if(!shared||shared.nodes.length<2)continue;const basin=fd.terminal_basins[shared.basin_index],payload={model:HYPERGRAPH_DERIVATION_MODEL,geometric_parent:g.hyperedge_id,coupled_classical_nodes:[...shared.nodes].sort(),terminal_members:basin.terminal_members};const hash=derivationHash(payload);out.push({schema:HYPEREDGE_SCHEMA,hyperedge_id:`hybrid.aspect_routing.${g.configuration_type}.${hash.slice(0,12)}`,hyperedge_class:'compound_hybrid',configuration_type:'aspect_dispositor_coupling',label:`${g.label} × Dispositor Basin`,participating_nodes:[...g.participating_nodes],participant_classes:{...g.participant_classes},required_cardinality:g.required_cardinality,geometric_metrics:{...g.geometric_metrics,parent_hyperedge_id:g.hyperedge_id},topological_metrics:{scc_id:`terminal.${basin.terminal_members.join('.')}`,is_closed_cycle:basin.terminal_members.length>=2,basin_volume:basin.basin_size,basin_fraction:basin.basin_fraction,basin_members:basin.basin_members,coupled_classical_nodes:[...shared.nodes].sort(),coupled_classical_count:shared.nodes.length},derivation_hash:hash,derivation_hash_algorithm:'sha-256',derivation:{model:HYPERGRAPH_DERIVATION_MODEL,calculation:'intersection of a verified geometric hyperedge with independently derived classical terminal-basin membership',parents:[g.hyperedge_id],payload},research_status:baseStatus(),null_profile:null,population_frequency:'unknown',interpretation_status:'withheld'})}
  return out.sort((a,b)=>a.hyperedge_id.localeCompare(b.hyperedge_id))}

export function buildIncidenceMatrix(vertices,hyperedges){const vertexIds=uniq(vertices.map(v=>typeof v==='string'?v:v.id)).sort(),edgeIds=hyperedges.map(e=>e.hyperedge_id),matrix=vertexIds.map(v=>hyperedges.map(e=>e.participating_nodes.includes(v)?1:0)),vertexDegree=Object.fromEntries(vertexIds.map((v,i)=>[v,matrix[i].reduce((a,b)=>a+b,0)])),hyperedgeDegree=Object.fromEntries(hyperedges.map(e=>[e.hyperedge_id,e.participating_nodes.length]));return {model:'naf.research.hypergraph_incidence.v0.4.7',vertex_ids:vertexIds,hyperedge_ids:edgeIds,H:matrix,D_v:vertexDegree,D_e:hyperedgeDegree,spectral_status:'incidence-only; normalized hypergraph Laplacian eigensystem deferred'}}
export function buildAstrologicalHypergraph({analysis=null,options={}}={}){if(!analysis)throw new Error('Hypergraph engine requires chart analysis');const vertices=hypergraphObjects(analysis,options),geometric=detectGeometricHyperedges(analysis,options),topological=detectTopologicalHyperedges(analysis),hybrid=detectCompoundHybridHyperedges(analysis,geometric),hyperedges=[...geometric,...topological,...hybrid],incidence=buildIncidenceMatrix(vertices,hyperedges);return deepFreeze({schema:'naf.research.astrological_hypergraph_result.v0.4.7',model_id:HYPERGRAPH_MODEL,version:HYPERGRAPH_VERSION,regime:'discovery',vertices,hyperedges,classes:{geometric_polygon:geometric.length,topological_basin:topological.length,compound_hybrid:hybrid.length},incidence,epistemic_contract:{layer_e_quarantined:true,detection_not_unexpectedness:true,null_profile_required_before_baseline_promotion:true,population_frequency:'unknown',interpretation:'withheld',no_scalar_strength_score:true},restrictions:['Hyperedges are exact objects under named geometric/topological rule models, not validated physical fields or psychological causes.','Modern configuration labels are template identifiers and are not silently attributed to Hellenistic doctrine.','No population-frequency language is permitted before a real cohort engine exists.']})}
