import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseChartInput} from '../src/kernel/noetic-kernel.mjs';
import {analyzeChartWithIntegrity} from '../src/kernel/hellenistic-integrity.mjs';
import {computeConditionSystem} from '../src/conditions/condition-system.mjs';
import {analyzeGraphArchitecture} from '../src/research/graph-analytics-engine.mjs';
import {buildHouseResonanceMap} from '../src/interpretation/house-resonance-engine.mjs';
import {buildModernRulershipOverlay} from '../src/interpretation/modern-rulership-overlay.mjs';
import {buildHouseRiver} from '../src/research/house-river-engine.mjs';
import {computeExtendedAspects} from '../src/research/aspect-family-engine.mjs';
import {buildV044DiscoverySuite} from '../src/research/v044-discovery-suite.mjs';
import {buildEvidencePack} from '../src/reading/evidence-pack.mjs';
import {buildAuditableReading} from '../src/reading/constrained-reading-engine.mjs';
import {normalizeReadingClaimProof} from '../src/reading/reading-claim-normalizer.mjs';
import {checkReadingIntegrity} from '../src/integrity/reading-integrity-checker.mjs';
import {buildDerivationIndexV044} from '../src/integrity/derivation-walker-v044.mjs';

const text=fs.readFileSync(new URL('./fixtures/audrey-chart.txt',import.meta.url),'utf8');
const analysis=analyzeChartWithIntegrity(parseChartInput(text));
const conditions=computeConditionSystem(analysis),graph=analyzeGraphArchitecture(analysis,conditions.primitive),resonance=buildHouseResonanceMap(analysis),modern=buildModernRulershipOverlay(analysis),river=buildHouseRiver(analysis),extended=computeExtendedAspects(analysis);
const discoveries=buildV044DiscoverySuite({analysis,conditions,graph,resonance,river,modern,extended});
const classical=[...graph.graphs.classical_dispositor.terminal_basins].sort((a,b)=>b.basin_size-a.basin_size);
assert.equal(classical.length,2);assert.deepEqual(classical.map(x=>[x.terminal_members.join('|'),x.basin_size]),[['Saturn',6],['Jupiter',1]]);
const full=discoveries.findings.find(x=>x.kind==='full_planet_basin_partition');assert.ok(full);assert.deepEqual(full.measurement.basins.sort((a,b)=>b.basin_size-a.basin_size).map(x=>[x.terminal_members.join('|'),x.basin_size]),[['Saturn',8],['Jupiter',2]]);
const hp=discoveries.findings.find(x=>x.kind==='house_terminal_partition');assert.ok(hp);assert.deepEqual(hp.measurement.partitions.map(x=>[x.terminal,x.house_count]),[['Saturn',10],['Jupiter',2]]);
assert.equal(river.planetary_bands.find(x=>x.from==='Mars'&&x.to==='Saturn').count,5);
const nep=modern.placements.find(x=>x.id==='Neptune');assert.equal(nep.modern_domicile,true);assert.equal(nep.traditional_sign_ruler,'Jupiter');
const parallel=discoveries.findings.find(x=>x.kind==='parallel_domicile'&&x.measurement.sign==='Pisces');assert.ok(parallel);assert.equal(parallel.measurement.same_house,true);
const pair=(a,b)=>extended.aspects.find(x=>new Set([x.a,x.b]).has(a)&&new Set([x.a,x.b]).has(b)&&x.aspect==='semi_sextile');assert.ok(pair('Jupiter','Saturn'));assert.ok(pair('Saturn','Neptune'));
const extras=[...discoveries.derivation_entries,...modern.ledger_entries,...extended.ledger_entries],index=buildDerivationIndexV044({analysis,primitive:conditions.primitive,relational:conditions.relational,compound:conditions.compound,houseRiver:river,extra:extras});
assert.equal(index.entries['coordinate:Sun'].kind,'coordinate');assert.equal(index.entries['whole_sign_house:Sun'].kind,'whole_sign_house');
const pack=buildEvidencePack({analysis,conditions,graph,resonance,river,discoveries}),reading=normalizeReadingClaimProof(buildAuditableReading(pack)),integrity=checkReadingIntegrity(reading,pack,index);
assert.equal(integrity.publication_gate.pass,true);assert.equal(integrity.blocked_claims.length,0);assert.ok(reading.claims.some(c=>c.text.includes('10/12 houses')));
console.log('v0.4.4 multi-basin + modern overlay + expanded aspects: ok');
