import assert from 'node:assert/strict';
import {runNullModelLaboratory,attachNullResultsToDiscoveryRegistry,describeNullModelLaboratory} from '../src/research/null-model-laboratory.mjs';
import {buildNullResearchState,degreeSequence} from '../src/research/null-state.mjs';
import {generateNullState,createDeterministicRng} from '../src/research/null-model-registry.mjs';
const lon={Sun:10,Moon:130,Mercury:40,Venus:70,Mars:100,Jupiter:250,Saturn:310};
const sign=x=>['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'][Math.floor(x/30)];
const objects=Object.entries(lon).map(([id,longitude])=>({id,type:'planet',longitude,sign:sign(longitude)}));
const aspects=[
 {a:'Sun',b:'Moon',aspect:'trine',orb_deg:0,separation_deg:120},{a:'Moon',b:'Jupiter',aspect:'trine',orb_deg:0,separation_deg:120},{a:'Sun',b:'Jupiter',aspect:'trine',orb_deg:0,separation_deg:120},
 {a:'Mercury',b:'Venus',aspect:'conjunction',orb_deg:0,separation_deg:30},{a:'Venus',b:'Mars',aspect:'conjunction',orb_deg:0,separation_deg:30},{a:'Mercury',b:'Mars',aspect:'conjunction',orb_deg:0,separation_deg:60},
 {a:'Mars',b:'Saturn',aspect:'square',orb_deg:0,separation_deg:90}
];
const analysis={kernel_version:'test',angles:{ASC:{id:'ASC',type:'angle',sign:'Leo',longitude:120}},objects,aspects,topology:{dispositor_graph:{edges:[]}}};
const conditions={relational:{relations:[{id:'r1',a:'Sun',b:'Moon',type:'test'}]},compound:{testimonies:[{id:'t1',target:'Jupiter',agents:['Sun']}],by_planet:{Sun:{presence:'bonified'},Moon:{presence:'none'},Mercury:{presence:'none'},Venus:{presence:'none'},Mars:{presence:'none'},Jupiter:{presence:'none'},Saturn:{presence:'none'}}}};
const discoveries={model_id:'test.discovery',findings:[{kind:'motif_cross_layer'},{kind:'multi_role'},{kind:'classical_basin_partition'},{kind:'house_convergence'}]};
const d=describeNullModelLaboratory();assert.equal(d.null_models.length,4);assert.equal(d.metrics.length,5);assert.equal(d.epistemic_contract.no_cross_null_aggregate_score,true);assert.ok(Object.isFrozen(d.null_models[0]));assert.ok(Object.isFrozen(d.null_models[0].preserves));assert.ok(Object.isFrozen(d.metrics[0]));assert.ok(Object.isFrozen(d.metrics[0].admissible_null_models));
const args={analysis,conditions,discoveries,iterations:199,seed:'fixed-seed'};const a=runNullModelLaboratory(args),b=runNullModelLaboratory(args);assert.equal(a.run_id,b.run_id);assert.deepEqual(a.experiments.map(x=>[x.raw_p,x.adjusted_p,x.null_distribution.values_hash]),b.experiments.map(x=>[x.raw_p,x.adjusted_p,x.null_distribution.values_hash]));
for(const e of a.experiments){assert.ok(e.raw_p>=1/200);assert.ok(e.raw_p<=1);assert.ok(e.adjusted_p>=e.raw_p-1e-12);assert.ok(e.adjusted_p<=1);assert.equal(e.no_cross_null_aggregate_score,true);assert.ok(['departure-detected','no-departure-detected'].includes(e.departure_evaluation));assert.equal(e.population_frequency,'unknown');assert.equal(e.interpretation_status,'withheld')}
assert.ok(a.families.every(f=>f.procedure==='benjamini_hochberg'));
const state=buildNullResearchState({analysis,conditions,discoveries}),rng=createDeterministicRng(123),nd=generateNullState('N_D',state,rng);assert.deepEqual(degreeSequence(nd),degreeSequence(state));assert.equal(nd._null_diagnostics.degree_sequence_preserved,true);const nt=generateNullState('N_T',state,createDeterministicRng(456));assert.equal(nt._null_diagnostics.rulership_multiplicity_preserved,true);
const registry={candidates:[{temporary_label:'motif_cross_layer',promotion_state:'detected-no-baseline',model_identity:{status:{null_comparison:'pending',population_frequency:'unknown',interpretation:'withheld',replication:'none',historical_analogue:'unexamined'}}},{temporary_label:'parallel_domicile',promotion_state:'detected-no-baseline',model_identity:{status:{null_comparison:'pending',population_frequency:'unknown',interpretation:'withheld'}}}]};const attached=attachNullResultsToDiscoveryRegistry(registry,a);assert.equal(attached.candidates[0].promotion_state,'null-tested');assert.equal(attached.candidates[0].model_identity.status.null_comparison,'completed');assert.equal(attached.candidates[0].model_identity.status.population_frequency,'unknown');assert.equal(attached.candidates[0].model_identity.status.interpretation,'withheld');assert.equal(attached.candidates[0].model_identity.status.replication,'none');assert.equal(attached.candidates[0].model_identity.status.historical_analogue,'unexamined');assert.equal(attached.candidates[1].promotion_state,'detected-no-baseline');assert.equal(attached.candidates[0].null_comparison.no_aggregate_score,true);
console.log('v0.4.6 null model laboratory: ok');
