import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseChartInput} from '../src/kernel/noetic-kernel.mjs';
import {analyzeChartWithIntegrity} from '../src/kernel/hellenistic-integrity.mjs';
import {computeConditionSystem} from '../src/conditions/condition-system.mjs';
import {analyzeGraphArchitecture} from '../src/research/graph-analytics-engine.mjs';
import {buildHouseRiver} from '../src/research/house-river-engine.mjs';
import {buildHouseResonanceMap} from '../src/interpretation/house-resonance-engine.mjs';
import {buildModernRulershipOverlay} from '../src/interpretation/modern-rulership-overlay.mjs';
import {computeExtendedAspects} from '../src/research/aspect-family-engine.mjs';
import {buildV044DiscoverySuite} from '../src/research/v044-discovery-suite.mjs';
import {runBrowserNullSuite} from '../src/research/null-lab-browser-integration.mjs';
const text=fs.readFileSync(new URL('./fixtures/audrey-chart.txt',import.meta.url),'utf8');
const analysis=analyzeChartWithIntegrity(parseChartInput(text)),conditions=computeConditionSystem(analysis),graph=analyzeGraphArchitecture(analysis,conditions.primitive),river=buildHouseRiver(analysis),resonance=buildHouseResonanceMap(analysis),modern=buildModernRulershipOverlay(analysis),extended=computeExtendedAspects(analysis),discoveries=buildV044DiscoverySuite({analysis,conditions,graph,resonance,river,modern,extended});
globalThis.__NAF_RESEARCH_CONTEXT__={analysis,graph,river,conditions,discoveries};
const a=runBrowserNullSuite({iterations:32,seed:'browser-regression'}),b=runBrowserNullSuite({iterations:32,seed:'browser-regression'});
assert.equal(a.nulls.tests.length,15);assert.equal(a.nulls.interpretation_status,'withheld');assert.equal(a.nulls.population_frequency_status,'not_measured');assert.equal(a.candidate_nulls.length,a.discovery.candidates.length);assert.match(a.nulls.source_state_fingerprint,/^fnv1a32:/);assert.deepEqual(a.nulls.tests.map(t=>t.null_distribution_summary.digest),b.nulls.tests.map(t=>t.null_distribution_summary.digest));
delete globalThis.__NAF_RESEARCH_CONTEXT__;delete globalThis.__NAF_V046_NULL_RESULT__;
console.log('v0.4.6 browser null adapter: ok');
