import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseChartInput} from '../src/kernel/noetic-kernel.mjs';
import {analyzeChartWithIntegrity} from '../src/kernel/hellenistic-integrity.mjs';
import {computeConditionSystem} from '../src/conditions/condition-system.mjs';
import {analyzeGraphArchitecture} from '../src/research/graph-analytics-engine.mjs';
import {buildHouseResonanceMap} from '../src/interpretation/house-resonance-engine.mjs';
import {buildModernRulershipOverlay} from '../src/interpretation/modern-rulership-overlay.mjs';
import {buildHouseRiver} from '../src/research/house-river-engine.mjs';
import {computeExtendedAspects} from '../src/research/aspect-family-engine.mjs';
import {buildV044DiscoverySuite} from '../src/research/v044-discovery-suite.mjs';
import {buildAstrologicalHypergraph} from '../src/research/hypergraph-engine.mjs';
import {runHypergraphNullLaboratory} from '../src/research/hypergraph-null-evaluator.mjs';
import {buildResearchLabV047} from '../src/research/research-lab-v047.mjs';

const text=fs.readFileSync(new URL('./fixtures/canonical-andrew-chart.txt',import.meta.url),'utf8');
const analysis=analyzeChartWithIntegrity(parseChartInput(text));
const conditions=computeConditionSystem(analysis),graph=analyzeGraphArchitecture(analysis,conditions.primitive),resonance=buildHouseResonanceMap(analysis),modern=buildModernRulershipOverlay(analysis),river=buildHouseRiver(analysis),extended=computeExtendedAspects(analysis),discoveries=buildV044DiscoverySuite({analysis,conditions,graph,resonance,river,modern,extended});
const hypergraph=buildAstrologicalHypergraph({analysis});
const before=buildResearchLabV047({analysis,conditions,graph,river,modern,extended,discoveries,hypergraph});
assert.equal(before.version,'0.4.7');
assert.equal(before.parent_research_lab.version,'0.4.6');
assert.equal(before.audit.pass,true);
assert.equal(before.aperture.default,'personal');
assert.ok(before.aperture.personal_rule.includes('hypergraph'));
assert.equal(before.formal_hypergraph.hyperedge_count,hypergraph.hyperedges.length);
assert.equal(before.formal_hypergraph.null_result,null);
assert.ok(hypergraph.hyperedges.every(h=>h.research_status.dimensions.null_comparison==='pending'));

const nulls=runHypergraphNullLaboratory({analysis,conditions,graph,river,discoveries,hypergraph,iterations:39,seed:'v047-research-lab'});
const after=buildResearchLabV047({analysis,conditions,graph,river,modern,extended,discoveries,hypergraph_null_results:nulls});
assert.equal(after.audit.pass,true);
assert.equal(after.formal_hypergraph.null_result.run_id,nulls.run_id);
assert.ok(after.formal_hypergraph.hyperedge_count>0);
assert.ok(nulls.hypergraph.hyperedges.every(h=>h.research_status.vector[2]===1));
assert.equal(after.counterfactual_boundary.population_frequency,'unknown-not-tested');
assert.equal(after.counterfactual_boundary.interpretation,'withheld');
assert.ok(after.constitution_refs.includes('pairwise edges and higher-order hyperedges are distinct research objects'));
console.log('v0.4.7 research lab wrapper: ok');
