import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseChartInput} from '../src/kernel/noetic-kernel.mjs';
import {analyzeChartWithIntegrity} from '../src/kernel/hellenistic-integrity.mjs';
import {computeConditionSystem} from '../src/conditions/condition-system.mjs';
import {analyzeGraphArchitecture} from '../src/research/graph-analytics-engine.mjs';
import {buildHouseResonanceMap} from '../src/interpretation/house-resonance-engine.mjs';
import {buildModernRulershipOverlay} from '../src/interpretation/modern-rulership-overlay.mjs';
import {buildHouseRiver} from '../src/research/house-river-engine.mjs';
import {computeExtendedAspects} from '../src/research/aspect-family-engine.mjs';
import {buildV044DiscoverySuite} from '../src/research/v044-discovery-suite.mjs';
import {buildResearchLab} from '../src/research/research-lab-engine.mjs';
const text=fs.readFileSync(new URL('./fixtures/audrey-chart.txt',import.meta.url),'utf8');
const analysis=analyzeChartWithIntegrity(parseChartInput(text));
const conditions=computeConditionSystem(analysis),graph=analyzeGraphArchitecture(analysis,conditions.primitive),resonance=buildHouseResonanceMap(analysis),modern=buildModernRulershipOverlay(analysis),river=buildHouseRiver(analysis),extended=computeExtendedAspects(analysis),discoveries=buildV044DiscoverySuite({analysis,conditions,graph,resonance,river,modern,extended});
const lab=buildResearchLab({analysis,graph,river,conditions,modern,extended,discoveries});
assert.equal(lab.audit.pass,true);assert.equal(lab.aperture.default,'personal');
const modernCmp=lab.comparisons.find(x=>x.hypothesis_id==='NAF-HYP-MODERN-OUTER-CORULERS-001');assert.ok(modernCmp.changed_fields.includes('overlay_annotations'));assert.equal(modernCmp.deltas.dispositor_edges.added.length,0);
const aspectCmp=lab.comparisons.find(x=>x.hypothesis_id==='NAF-HYP-EXPANDED-ASPECT-FAMILY-001');assert.ok(aspectCmp.changed_fields.includes('supplemental_aspects'));assert.equal(aspectCmp.deltas.canonical_aspects.added.length,0);
const pending=lab.comparisons.find(x=>x.hypothesis_id==='NAF-HYP-CERES-TAURUS-001');assert.equal(pending.status,'registered-not-executed');
assert.equal(lab.discovery.count,discoveries.findings.length);assert.ok(lab.discovery.candidates.every(c=>c.model_identity.status.null_comparison==='pending'));
assert.ok(lab.constitution_refs.some(x=>x.includes('surprising its creators')));
console.log('v0.4.5 research lab integration: ok');
await import('./null_model_v046_smoke.mjs');
await import('./network_null_v046_smoke.mjs');
