import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
const html=fs.readFileSync(new URL('../prototype/v0413.html',import.meta.url),'utf8');
assert.match(html,/Noetic Atlas v0\.4\.1\.3/);
assert.match(html,/Structure & Analysis/);
assert.match(html,/Resonance Field/);
assert.match(html,/v0412c\.html\?build=v0413-preserved-observatory/);
assert.match(html,/house-resonance-engine\.mjs/);
assert.match(html,/Ascensional Phase Map/);
assert.match(html,/Element–Mode Resonance Lattice/);
assert.match(html,/natural-house resonance/i);
assert.match(html,/actual Whole Sign/i);
assert.match(html,/same serialized chart state/i);
const moduleMatch=html.match(/<script type="module">([\s\S]*?)<\/script>/);assert.ok(moduleMatch);new vm.Script(`(async()=>{${moduleMatch[1].replace(/^import .*$/gm,'')}\n})`);
const preserved=fs.readFileSync(new URL('../prototype/v0412c.html',import.meta.url),'utf8');
assert.match(preserved,/Energetic Analysis/);assert.match(preserved,/Graph Findings/);assert.match(preserved,/Metrics/);assert.match(preserved,/Condition/);assert.match(preserved,/Integrity/);assert.match(preserved,/Loading analysis/);
const hash=crypto.createHash('sha256').update(preserved).digest('hex');assert.equal(hash.length,64);
console.log('v0.4.1.3 preserved additive UI contract smoke: ok');