import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../prototype/v042.html',import.meta.url),'utf8');
assert.match(html,/Noetic Atlas <span[^>]*>v0\.4\.2/);
assert.match(html,/src="\.\/v0413\.html\?build=v042-preserved-v0413"/);
assert.match(html,/Existing Atlas/);
for(const label of ['Qualified Resonance','Relations','Qualified Flow','House River','Proof Walker'])assert.match(html,new RegExp(label));
assert.match(html,/computeConditionSystem/);
assert.match(html,/buildHouseResonanceMap/);
assert.match(html,/buildHouseRiver/);
assert.match(html,/buildDerivationIndex/);
assert.match(html,/walkDerivation/);
assert.match(html,/renderConditionSignatureHTML/);
assert.match(html,/one chart state/i);
assert.match(html,/integer number of house-ruler paths/i);
assert.match(html,/Reception does not replace dispositorship/i);
assert.match(html,/data-proof/);
assert.match(html,/MutationObserver/);
const moduleMatch=html.match(/<script type="module">([\s\S]*?)<\/script>/);assert.ok(moduleMatch,'module script exists');
const syntaxOnly=moduleMatch[1].replace(/^import .*$/gm,'');new vm.Script(`(async()=>{${syntaxOnly}\n})`);
const entry=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(entry,/prototype\/v042\.html\?build=relational-042/);
assert.match(entry,/Noetic Atlas v0\.4\.2/);
console.log('v0.4.2 additive relational UI + public entry contract: ok');
