import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../prototype/v043.html',import.meta.url),'utf8');
assert.match(html,/Noetic Atlas <span[^>]*>v0\.4\.3/);
assert.match(html,/src="\.\/v042\.html\?build=v043-preserved-v042"/);
for(const label of ['Existing Atlas','Compound Condition','Compound Map','Proof Walker','Source Boundary'])assert.match(html,new RegExp(label));
assert.match(html,/ONE CHART STATE → MANY COORDINATED PROJECTIONS/);
assert.match(html,/same deterministic chart state/i);
assert.match(html,/does not calculate astronomy, houses, aspects, lots, or kernel topology/i);
assert.match(html,/computeConditionSystem/);
assert.match(html,/conditions\.compound/);
assert.match(html,/buildDerivationIndex\(\{analysis,primitive:conditions\.primitive,relational:conditions\.relational,compound:conditions\.compound\}\)/);
assert.match(html,/walkDerivation/);
assert.match(html,/No net score exists/);
assert.match(html,/Multiple testimonies may coexist/);
assert.match(html,/Ambiguous historical reconstructions are retained as deferred states/i);
assert.match(html,/data-proof/);
assert.match(html,/MutationObserver/);
const moduleMatch=html.match(/<script type="module">([\s\S]*?)<\/script>/);assert.ok(moduleMatch,'module script exists');
const syntaxOnly=moduleMatch[1].replace(/^import .*$/gm,'');new vm.Script(`(async()=>{${syntaxOnly}\n})`);
const root=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(root,/prototype\/v043\.html\?build=compound-043/);
assert.match(root,/Noetic Atlas v0\.4\.3/);
console.log('v0.4.3 additive compound UI + public entry contract: ok');
