import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../prototype/v044.html',import.meta.url),'utf8');
assert.match(html,/Noetic Atlas/);
assert.match(html,/v0\.4\.4 candidate/i);
for(const label of ['Chart','Reading','Resonance','Network','House Flow','Condition','Proof'])assert.match(html,new RegExp(`>${label}<`));
assert.equal((html.match(/<iframe\b/g)||[]).length,1,'v044 remains a flat shell with one deterministic-core iframe');
assert.match(html,/src="\.\/index\.html\?build=v044-core"/);
assert.doesNotMatch(html,/src="\.\/v04(?:12c|13|2|3)\.html/);
for(const name of ['buildEvidencePack','buildAuditableReading','checkReadingIntegrity','buildCrossLayerDiscoveries'])assert.match(html,new RegExp(name));
assert.match(html,/structural provenance/i);
assert.match(html,/blocked claims/i);
assert.match(html,/data-claim-proof/);
assert.match(html,/detected-no-null-model/);
assert.match(html,/natural-house comparison is secondary/i);
const moduleMatch=html.match(/<script type="module">([\s\S]*?)<\/script>/);assert.ok(moduleMatch);
const syntaxOnly=moduleMatch[1].replace(/^import .*$/gm,'');new vm.Script(`(async()=>{${syntaxOnly}\n})`);
console.log('v0.4.4 auditable-reading candidate UI contract: ok');
