import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../prototype/v046.html',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../src/research/null-model-worker.mjs',import.meta.url),'utf8');
assert.match(worker,/runNullModelLaboratory/);assert.match(worker,/self\.onmessage/);assert.match(worker,/postMessage/);
assert.match(html,/Noetic Atlas v0\.4\.6/);
assert.equal((html.match(/<iframe\b/g)||[]).length,1);
assert.match(html,/data-aperture="personal"/);
assert.match(html,/data-aperture="research"/);
assert.match(html,/Run null tests/);
assert.match(html,/null-model-worker\.mjs/);assert.match(html,/new Worker/);
assert.match(html,/Research mode never auto-runs simulations/);
assert.match(html,/finite Monte Carlo \+1 correction/i);
assert.match(html,/benjamini.?hochberg/i);
assert.match(html,/null profile/i);
assert.match(html,/not a pass-count/i);
assert.match(html,/population frequency/i);
assert.match(html,/interpretation/i);
const views=[...html.matchAll(/data-view="([^"]+)"/g)].map(m=>m[1]);
assert.deepEqual(views,['chart','reading','resonance','network','houseflow','condition','proof']);
const explicitRun=html.indexOf('b.onclick=()=>');
const workerPost=html.indexOf("nullWorker.postMessage({type:'run'");
assert.ok(explicitRun>=0&&workerPost>explicitRun,'null simulations must be initiated by the explicit run handler');
console.log('v0.4.6 UI contract: ok');
